### PR TITLE
Feature: add ability create temp table if supported

### PR DESCRIPTION
**Pull request by AdamVyborny**
JIRA: https://keboola.atlassian.net/browse/PST-1868

Replaces #54

### CODE REVIEW

**Comment by lotharschulz** [comment]
LGTM, thanks @AdamVyborny

**Comment by lotharschulz** [comment]
fix: #55

**Review by MiroCillik — APPROVED** [review]
Promin, mi to zapadlo, LGTM

**Comment by lotharschulz** [comment]
I am not sure I understand, can this be merged @MiroCillik & @AdamVyborny ?

**Comment by AdamVyborny** [comment]
> I am not sure I understand, can this be merged @MiroCillik & @AdamVyborny ?

It is released, so now you can try it in platform by adding that parameter into configuration via raw mode as it is not added to UI. In case you don’t know, you can access raw mode just by adding `/raw` to the end of URL of configuration you want to edit.

**Comment by lotharschulz** [comment]
I let Seckin and team know.

**Pull request merged**
